<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46725" started-at="2017-02-24T11:26:04Z" finished-at="2017-02-24T11:26:50Z">
    <groups>
      <group name="Recharge">
        <method signature="Testscript.RechargePending()[pri:0, instance:com.Tapzo.CustomerSupport.Testscript@6d026701]" name="RechargePending" class="com.Tapzo.CustomerSupport.Testscript"/>
      </group> <!-- Recharge -->
    </groups>
    <test name="Default test" duration-ms="46725" started-at="2017-02-24T11:26:04Z" finished-at="2017-02-24T11:26:50Z">
      <class name="com.Tapzo.CustomerSupport.Testscript">
        <test-method status="FAIL" signature="RechargePending()[pri:0, instance:com.Tapzo.CustomerSupport.Testscript@6d026701]" name="RechargePending" duration-ms="46698" started-at="2017-02-24T16:56:04Z" finished-at="2017-02-24T16:56:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Answer is wrong(Answer id=67) and 
 answer=Your recharge transaction is delayed due to a technical problem on the operator side.  expected [64] but found [67]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Answer is wrong(Answer id=67) and 
 answer=Your recharge transaction is delayed due to a technical problem on the operator side.  expected [64] but found [67]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at Utility.Utilities.validateAnswer(Utilities.java:87)
	at com.Tapzo.CustomerSupport.Testscript.RechargePending(Testscript.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RechargePending -->
      </class> <!-- com.Tapzo.CustomerSupport.Testscript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
